### ISSUE TITLE
Exploration 2

### ISSUE THREAD

**Issue by jwbowers** [bowers-grad-stats-illinois/530-explorations#7]
Exporation 2 is now available:

https://classroom.github.com/assignment-invitations/2d0dc3b9e2187c405585183deeaa202b

The (syllabus)[http://jakebowers.org/PS530/syllabus.pdf] is also updated with some suggested readings to help with the assignment. The readings will be on the moodle in a few minutes.

**Comment by drenn2** [comment]
Two quick things: 

1) Turns out that clicking the classroom link makes a new repository in our organization, which probably isn't something people will want to sort through as we move forward. Please just update your ps530/ps531 exploration repositories by pulling the new files. (The little arrow in the git panel that is blue(?)). If you made some changes, there are ways to stash them or you could rename them (check google/stackoverflow), but for for most people the following command will suffice: 

git reset --hard HEAD

You'll need to use the shell interface to do this. In RStudio, you can access this via the "gear" icon in the git panel, and selecting "shell..." 

2) Send me questions if you like. I am done with my APSA duties... finally. I will push comments and examples to the "uips-stat-share" repository that is shared between both PS530 and 531.
